### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [dcrisanto/lim-2018-05-bc-core-am-datadashboard#25]
**HTML**
* No olvides validar tu HTML, revisa [esta URL](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdcrisanto.github.io%2Flim-2018-05-bc-core-am-datadashboard%2Fsrc%2F) para que observes tus errores y advertencias.
* Te sugerimos usar más etiquetas semánticas como `<header>`, y `<footer>`.

**JS**
* Ten en cuenta que tu código debe funcionar en cualquier caso (con cualquier _id_ de unidades o partes). Te recomendamos que recorras la data de manera dinámica en lugar usar identificadores específicos. Con un curso diferente a _intro_, tu aplicación dejaría de funcionar.
* Tener cuidado con el uso de variables que nunca fueron declaradas (`data.js`: part).
* Revisar que no se usen `;` no requeridos.
* No olvides eliminar tus invocaciones al _console.log_.

**GitHub**
* No olvides el uso de los issues y milestones para la organización y asignación de responsabilidades. Te ayudará a llevar un seguimiento de su progreso.

**Tests**
* Realizar los tests era una parte requerida en el proyecto. La tabla que muestra la cobertura de tests no es válida o relevante si existen tests que no llegan a pasar.

Buen trabajo!

**Comment by dcrisanto** [comment]
@gaposx 
Gonzalo una consulta con respecto a lo que indicaste sobre el curso intro, la aplicación si recorre todos los cursos, no solo intro.
Sobre los test sólo  test no nos corrió que fue el de filter pero indicas que son más de  test que no pasaron.

**Comment by gaposx** [comment]
Hola!

> Gonzalo una consulta con respecto a lo que indicaste sobre el curso intro, la aplicación si recorre todos los cursos, no solo intro.

Me refiero a este código:
```javascript
user.stats.exercises['total'] = (Object.keys(unitsOfCourses['02-variables-and-data-types']['parts']['06-exercises']['exercises'])).length;
user.stats.exercises['completed'] = unitsOfCourses['02-variables-and-data-types']['parts']['06-exercises']['exercises']['01-coin-convert']['completed'] + unitsOfCourses['02-variables-and-data-types']['parts']['06-exercises']['exercises']['02-restaurant-bill']['completed'];
user.stats.exercises['percent'] = Math.round(((unitsOfCourses['02-variables-and-data-types']['parts']['06-exercises']['completed']) * 100));
```
Estos identificadores de unidades y partes existen sólo en el curso `intro`.

> Sobre los test sólo test no nos corrió que fue el de filter pero indicas que son más de test que no pasaron.

Te paso la captura del output al correr los tests.
![output_tests](https://user-images.githubusercontent.com/539819/42708147-f5b9758c-86a1-11e8-907c-c52659143fd4.png)
